# Generated by Django 4.0.3 on 2022-07-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCSapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='organizerName',
            field=models.CharField(max_length=32, null=True, verbose_name='Наименование организации проводящей турнир'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='theNumberOfTeamsRequiredToStartTheCompetition',
            field=models.IntegerField(default=4, verbose_name='Необходимое количество команд'),
        ),
    ]
